[build]
  command = """
    echo "Installing pnpm..." && \
    npm install -g pnpm && \
    echo "Installing dependencies..." && \
    pnpm install --no-frozen-lockfile && \
    echo "Starting build..." && \
    pnpm run build --verbose
  """
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "true"
  PNPM_FLAGS = "--no-frozen-lockfile --strict-peer-dependencies=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 