[build]
  command = """
    node -v && \
    echo "Installing pnpm..." && \
    npm install -g pnpm@latest && \
    pnpm -v && \
    echo "Installing dependencies..." && \
    pnpm install --no-frozen-lockfile --shamefully-hoist && \
    echo "Starting build..." && \
    NODE_ENV=production pnpm run build
  """
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 